# Name of your workflow
name: My Test Workflow

# Define the trigger event(s)
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs: 

  # Jobs to print something out
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, GitHub Actions!"

  # Job to build and test our template code
  build-and-test:
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y build-essential python3

      - run: pwd

      - name: Build app
        run: cmake -B build; cmake --build build